#server:
#  port: 8761

#spring:
#  application:
#    name: user-service

#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#      preferIpAddress: true

#spring:
#  application:
#    name: spring-cloud-eureka-client
#server:
#  port: 0
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    preferIpAddress: true